# Generated by Django 6.1.1 on 2026-10-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('hackathon', 'Hackathon'), ('social', 'Social'), ('multi-company', 'Multi-company'), ('learning', 'Learning')], default='social', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.CharField(blank=True, help_text='e.g. cybersecurity, climbing, CV help', max_length=120),
        ),
    ]
