# Generated by Django 6.1.1 on 2026-10-03 12:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('hackathon', 'Hackathon'), ('social', 'Social'), ('multi-company', 'Multi-company'), ('learning', 'Learning / CPD')], default='social', max_length=20)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, help_text='Place or link', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1 - Drained'), (2, '2 - Low'), (3, '3 - OK'), (4, '4 - Good'), (5, '5 - Great')])),
                ('note', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('health', 'Health & Fitness'), ('study', 'Study / Uni'), ('career', 'Career / Skills'), ('money', 'Money'), ('social', 'Social'), ('home', 'Home & Life admin')], default='career', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('goal', 'Goal step'), ('chore', 'Household'), ('study', 'Study'), ('rest', 'Rest / Recharge'), ('social', 'Social')], default='goal', max_length=20)),
                ('minutes', models.PositiveIntegerField(default=30, help_text='How long in minutes')),
                ('energy_cost', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='fivenine.goal')),
            ],
        ),
    ]
