# Generated by Django 6.1.1 on 2026-10-03 13:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fivenine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='energylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('planner', '📋 Planner — I love a routine'), ('spontaneous', '🎲 Go-with-the-flow'), ('balancer', '⚖️ A bit of both')], default='balancer', max_length=20)),
                ('chronotype', models.CharField(choices=[('early', '🌅 Early bird — best right after work'), ('night', '🦉 Night owl — best later in the evening'), ('either', '🤷 Either — energy decides')], default='either', max_length=20)),
                ('evenings_per_week', models.PositiveSmallIntegerField(default=4, help_text='Evenings per week you want planned (1-7)')),
                ('minutes_per_evening', models.PositiveSmallIntegerField(default=120, help_text='Free minutes on a typical evening')),
                ('social_balance', models.CharField(choices=[('self', '🔋 Mostly me-time (recharge solo)'), ('balanced', '⚖️ Balanced social + self'), ('social', '🎉 Mostly social (recharge with people)')], default='balanced', max_length=20)),
                ('task_style', models.CharField(choices=[('few_big', '🧱 Few bigger tasks per evening'), ('many_small', '🧩 Many small tasks per evening')], default='many_small', max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated, e.g. Python, presenting, CAD', max_length=300)),
                ('calendar_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('quiz_done', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
