# Generated by Django 6.1.1 on 2026-10-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fivenine', '0002_energylog_user_goal_user_task_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chronotype',
            field=models.CharField(choices=[('early', 'Early bird — best right after work'), ('night', 'Night owl — best later in the evening'), ('either', 'Either — energy decides')], default='either', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_type',
            field=models.CharField(choices=[('planner', 'Planner — I love a routine'), ('spontaneous', 'Go-with-the-flow'), ('balancer', 'A bit of both')], default='balancer', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_balance',
            field=models.CharField(choices=[('self', 'Mostly me-time (recharge solo)'), ('balanced', 'Balanced social + self'), ('social', 'Mostly social (recharge with people)')], default='balanced', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='task_style',
            field=models.CharField(choices=[('few_big', 'Few bigger tasks per evening'), ('many_small', 'Many small tasks per evening')], default='many_small', max_length=20),
        ),
    ]
