# Generated by Django 6.1.1 on 2026-10-03 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fivenine', '0003_alter_userprofile_chronotype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='topic',
            field=models.CharField(blank=True, help_text='e.g. cybersecurity, climbing, CV help', max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Set to make this a sub-task of another task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='fivenine.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Optional start time, e.g. 18:30', null=True),
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='fivenine.communityevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
