# Generated by Django 6.1.1 on 2026-10-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fivenine', '0005_task_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityevent',
            name='kind',
            field=models.CharField(choices=[('hackathon', 'Hackathon'), ('social', 'Social'), ('multi-company', 'Multi-company'), ('learning', 'Learning')], default='social', max_length=20),
        ),
    ]
