# Generated by Django 6.1.1 on 2026-10-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fivenine', '0006_alter_communityevent_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
    ]
