# Generated by Django 6.1.1 on 2026-10-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_apprentice_user_and_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprentice',
            name='free_time_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours a day to keep free of activities.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='apprentice',
            name='work_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apprentice',
            name='work_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
